### ISSUE TITLE
Footer covers app

### ISSUE THREAD

**Issue by kamicut** [kamicut/vote-here-2016#4]
Happens on some Android landscape phones.

**Comment by chaficnajjar** [comment]
There is more than one way to approach this. One solution would be to rearrange the layout of the window in a responsive manner so that the contents fit on the screen of a phone in landscape orientation. Another solution would be to have the footer fixed to the bottom of the page, which will prevent the footer from covering the window but will require the user to scroll down to see whole form. A third solution which can be used along with the previous two is to decrease font sizes, margins, etc. on mobile.

I recommend using the first and third solutions together. Let me know which approach suits you would prefer.

**Comment by kamicut** [comment]
I removed the footer and incorporated it in the main div. I'll look into reducing the margin sizes for mobile.
